### ISSUE TITLE
XKOS Best Practices: Section F2. Link to RAMON

### ISSUE THREAD

**Issue by ChLaaboudi** [linked-statistics/xkos#165]
From <http://linked-statistics.github.io/xkos/xkos-best-practices.html#classifications-actors>
At the European level, Eurostat coordinates the consultation of Member States and establishes a timetable for the joint revision or updating of classifications. Eurostat offers a variety of information in paper, electronic and online formats, e.g. **[RAMON**](http://ec.europa.eu/eurostat/ramon/index.cfm?TargetUrl=DSP_PUB_WELC), the Eurostat metadata server.
	
RAMON will be phased out at the end of June 2023 and must be replaced by  : 
e.g. Eurostat classifications: https://ec.europa.eu/eurostat/data/classifications

**Comment by tfrancart** [comment]
Hello @ChLaaboudi the provided URL https://ec.europa.eu/eurostat/data/classifications gives a 404 error. Should we change it to https://ec.europa.eu/eurostat/data ?

Or I see that the RAMON URL redirects to https://ec.europa.eu/eurostat/web/metadata/classifications - should we use this one ?

Thanks

**Comment by tfrancart** [comment]
I have actually inserted both links in the PR

**Comment by ChLaaboudi** [comment]
Dear @tfrancart,
https://ec.europa.eu/eurostat/web/metadata/classifications is the correct one.
Best regards,
Christine

**Comment by DesNasiopoulou** [comment]
Dear @tfrancart,

While the link points well to the [Eurostat's Classifications page], the accompanying text needs an update. The textual reference to RAMON needs to be replaced with the reference to Eurostat Classifications page.

Best regards,
Despoina (Eurostat)

**Comment by tfrancart** [comment]
> The textual reference to RAMON needs to be replaced with the reference to Eurostat Classifications page.

I don't understand. There is no more textual reference to RAMON in the PR. Please bear in mind that the modifications have been made in a PR that is not yet approved and that the current online version of the document does not contain the change.
Or maybe I missed something, can you be more specific in that case ?
Thanks

**Comment by DesNasiopoulou** [comment]
Dear @tfrancart,

The online version, http://linked-statistics.github.io/xkos/xkos-best-practices.html,  contains the link update but not the textual modification. I understand that the modification is already made in the PR, thanks for the clarification.

Despoina
