### ISSUE TITLE
XKOS Best Practices: F.3.1

### ISSUE THREAD

**Issue by ChLaaboudi** [linked-statistics/xkos#166]
From <http://linked-statistics.github.io/xkos/xkos-best-practices.html#classifications-on-activities-products-and-goods> 
	
_Add_ (_Sections_, _Divisions_) , (_Groups_, _Classes)_

As an example, the ISIC classification is derived at the European level through the NACE.
ISIC (International Standard Industrial Classification of all Economic Activities of the United Nation) is the reference classification and NACE has the same structure. The first two levels **(Sections, Divisions)** are identical between NACE and ISIC, while levels three and four **(Groups, Classes)** are subdivisions of the corresponding levels of the ISIC classification.

**Comment by tfrancart** [comment]
OK @tfrancart to implement
