### ISSUE TITLE
XKOS Best Practices: F.4.2 (PRODCOM / CPC --> CPA)

### ISSUE THREAD

**Issue by ChLaaboudi** [linked-statistics/xkos#167]
From <http://linked-statistics.github.io/xkos/xkos-best-practices.html#different-point-of-view-on-the-same-domain-area-prodcom-cpc-or-hs-cn> 

_CPC must be replaced by CPA_

F.4.2 Different point of view on the same domain area (ProdCom / **CPA**, or HS / CN)
	Prodcom stands for "PRODuction COMmunautaire". This classification provides statistics on the production of manufactured goods by enterprises on the national territory of reporting countries. Prodcom . It covers mining and manufacturing: sections B and C of the statistical classification of economic activities in the European Union (NACE Rev. 2). Prodcom statistics aim to provide a comprehensive picture at EU level of the development of industrial production for a given product or sector, so that comparisons can be made between countries.
	The scope of ProdCom is thus different, and smaller, from the one of **CPA** , and there is a correspondence table to that subpart of the **CPA** .
	
Description from  the PRODCOM conceptScheme: https://showvoc.op.europa.eu/#/datasets/ESTAT_PRODCOM_List_2022/data 

> _PRODCOM is the title of the EU production statistics for Mining, Quarrying and Manufacturing that comes from the French title "PRODuction COMmunautaire" (Community production). PRODCOM headings are directly derived from NACE and the CPA. The first four digits of a PRODCOM code refer to the NACE classification, and the first six digits refer to the CPA classification. The last two digits are created specifically for PRODCOM. Most eight-digit PRODCOM codes have a complete reference to the Combined Nomenclature (CN) that means a full comparability between data from PRODCOM and data from foreign trade classified by the Combined Nomenclature._

**Comment by tfrancart** [comment]
OK - @tfrancart to implement the change
