### ISSUE TITLE
XKOS Best Practices: legal basis (eli:based_on)

### ISSUE THREAD

**Issue by ChLaaboudi** [linked-statistics/xkos#168]
eli:based_on is mostly associated to the European Legal Identifier and may be most appropriate for describing the EU Classifications.
Shoudn't we propose dc:conformTo at a larger level?

**Comment by tfrancart** [comment]
eli:based_on has a generic domain eli:Work, so it is OK to use it to describe something else than legislation, in our case statistical classifications.

**Comment by tfrancart** [comment]
@dzkwsk and @FranckCo : what is your opinion on this ? We have used eli:based_on in the BP document. This is correct from a formal domain/range point of view, and really precise in terms of semantics. dct:conformsTo is a more widely used property, but less precise. Any opinion ?

**Comment by tfrancart** [comment]
We leave it as it is.
Note : it is always possible for implementers to use other properties than those listed in the table, such as dct:conformsTo.
