### ISSUE TITLE
Review response: Antoine Isaac

### ISSUE THREAD

**Issue by wlthomas** [linked-statistics/xkos#26]
FROM: aisaac@few.vu.nl

Dear all,

 This is a response to the call for comments on the recent DDI draft vocabularies:
http://lists.w3.org/Archives/Public/public-esw-thes/2014May/0014.html

 First I apologise for the quite late feedback. Also, for obvious reasons (i.e., my interest for all things SKOS) I've focused my feedback only on the XKOS vocabulary,
http://rdf-vocabulary.ddialliance.org/xkos.html
 I copy the SKOS list.

 First, I'd like to say it's really good to see such work happening. The statistical classifications are important, and if SKOS is not enough to capture the requirements to represent them appropriately, then something must be done!

 Generally I also found the document is really good. I'm not an expert in the details of statistical classifications, but I think I understood quickly the gist of the problems and the appropriateness of the patterns to solve them ...
 In accordance to this positive feeling, I'm not questioning much the identified requirements. It is mostly about some of the decisions to mint new elements to tackle them, instead of re-using constructs from existing vocabularies.

 I hope this will be helpful!

 Best regards,

 Antoine Isaac

 -----

 - xkos:supersedes and xkos:succeeds. Can't they be expressed with dcterms:replaces and some existing versioning mechanisms? The definition of dcterms:replaces covers "supplanted, displaced or superseded" (http://dublincore.org/documents/dcmi-terms/#terms-replaces).
 In case you'd be interested, the SKOS wiki has a list of relevant work:
http://www.w3.org/2001/sw/wiki/SKOS/Issues/ConceptEvolution
 I think there has been progress on this recently, notably for the STW thesaurus
http://dcevents.dublincore.org/IntConf/dc-2013/paper/view/152/168

 - skos:belongsTo. why not re-use skos:inScheme? (even if it isn't in the same direction)

 - xkos:covers amd xkos:classifiedUnder. Their semantics are not really clear to me. More precisely: couldn't one of them or both be replaced by dcterms:subject or foaf:topic or foaf:primaryTopic?

 - xkos:Correspondence and xkos:ConceptAssociation. at the beginning it was unclear to me, but the example in 10.3 (really important for understanding!) convinced me this was a situation like ones in the ontology mapping community, where the EDOAL format uses an 'Alignment' class with 'Cells' for the individual correspondence. I reckon that the XKOS cases may be too far from the ontology matching ones, to your taste. Still, trying to stick as much as possible to existing terminology could be good. I'd have thought 'Alignment' to be better name for the role currently played by xkos:Correspondance' and 'correspondence' to be rather for xkos:ConceptAssociation.

 Also, the choice that is currently made surprises me as one that is not very granular on the side of sourceConcept and targetConcept statements: concepts are individually attached to the Association instance. Isn't there a need to create 'bundles' with certain semantic flavor for both source and target of the association? I'd have thought the reification to happen rather at this level. The representation of one-to-many mappings 'AND', 'OR' mappings has been a long-standing problems in the SKOS community (http://www.w3.org/2006/07/SWD/track/issues/131).
 One of the basic patterns available is the combination/coordination of concepts, as done in the MADS vocabulary (see the use of madsrdf:componentList at http://www.loc.gov/standards/mads/rdf/#t22 to link a bundle of concepts to the list of its components).
 If XKOS has cases that needs them, it would be interesting if the old proposals for SKOS mappings (http://www.w3.org/2004/02/skos/mapping/spec/2004-11-11.html) could be revived!

 - xkos:generalizes/xkos:specializes and xkos:hasPart/xkos:isPartOf. wouldn't the properties of the thesaurus standard ISO 25964 (broaderGeneric) skos-thes:broaderGeneric/skos-thes:narrowerGeneric and skos-thes:broaderPartitive/skos-thes:narrowerPartitive appropriate for this? This would be a great way to link standards of different communities, which I believe are really compatible together.

**Comment by FranckCo** [comment]
Thanks for these very interesting comments, Antoine, and thanks for the references that you mention.

I have broken down the list into several issues (28 to 32) so that it is easier to address each point.

So I am closing this one.
