### ISSUE TITLE
incorrect mapping to skos

### ISSUE THREAD

**Issue by PaulZH** [linked-statistics/xkos#27]
I'm afraid some parts of XKOS are not correctly mapped to SKOS.

E.g.
xkos:hasPart is a sub-type of skos:broader
xkos:isPartOf is a sub-type of skos:narrower
If I say :x xkos:hasPart :y, then I am saying that :x is bigger/broader/containing :y.
Following your specification, 
I'm saying then also :x skos:broader :y, which semantics are :x has broader :y.
Which is precisely the opposite of what has been previously said.

Figure 9 shows it correctly where hasPart is mapped to narrower.

But http://rdf-vocabulary.ddialliance.org/xkos.rdf also contains the error.

**Comment by FranckCo** [comment]
Hi Paul

Thanks for noticing that, I will push the correction in the next few days.

Franck

**Comment by PaulZH** [comment]
Hi Frank,

I still do not see the correction.

Paul

**Comment by yyz1989** [comment]
Is it that difficult??

**Comment by PaulZH** [comment]
No, It's not difficult. A change which can be made in 5 minutes by the editor.

Paul


On 26 Jan 2016, at 18:55, Yang <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it that difficult??

-

**Comment by FranckCo** [comment]
Fixed in commit  61f5f6d, I hope I have got it right this time. Sorry it took so long.

**Comment by PaulZH** [comment]
Will have a look shortly.


Paul
