### ISSUE TITLE
skos:belongsTo: why not re-use skos:inScheme?

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/xkos#29]
This is one of the comments made by Antoine Isaac (see issue #26):

skos:belongsTo. why not re-use skos:inScheme? (even if it isn't in the same direction)

**Comment by FranckCo** [comment]
‘belongsTo’ is used to attach a classification scheme (i.e. a major version of a classification) to the overarching classification. For example, ISIC Rev.1, ISIC Rev.2, ISIC Rev.3, ISIC Rev.3.1 and ISIC Rev.4 all belong to the ISIC classification, represented as a skos:Concept.

But the classification itself is not a concept belonging to any of the ISIC version (it is not an activity, to start with), so expressing that the ‘ISIC’ skos:Concept is included (skos:inScheme) in any of the ‘ISIC Rev.x’ skos:ConceptScheme would be inappropriate.

**Comment by wlthomas** [comment]
I think you can close but that first paragraph in the comment above is a good example of its use and should be included in the documentation.

**Comment by FranckCo** [comment]
I think that the specification already contains a similar example in section 5.1, so adding the first paragraph above would be just repetition.
