### ISSUE TITLE
Add a plainText Datatype property

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/xkos#36]
The instances of xkos:ExplanatoryNote are the resources to which it is possible to attach the different properties of the explanatory notes.

For most of those properties (eg. author, version, publishing date, etc.), existing properties from standard vocabularies (DC, PAV) can be used, and a best practice document on XKOS will provide advice on which properties to chose and how to use them.

For the text of the note, a mechanism borrowed to Eurovoc can be used: the http://eurovoc.europa.eu/schema#noteLiteral property takes an XML literal as object and allows to express the text of the note as an XHTML fragment (see for example http://id.insee.fr/codes/nafr2/sousClasse/27.11Z/noteContenuLimite).

But in many occasions, you just need the plain text content of the note, without formatting or structuration (in particular when you don't have any indication on formatting from the original source).

The 'plainText' datatype property is proposed for this usage. Its domain is xkos:ExplanatoryNote and its type is xs:string.

**Comment by cygri** [comment]
Not entirely convinced. Whether the value is XML or HTML or plain text is usually indicated by the datatype of the literal, not by the property. That's why the datatypes `rdf:XMLLiteral` and `rdf:HTML` exist. Also, setting the range to `xsd:string` means that language tags are disallowed.

**Comment by FranckCo** [comment]
Currently, we use a modelization inspired by what is done in Eurovoc:
- the *Note property points links the classification item to a resource <N> (which issue #33 suggests to be of type ExplanatoryNote).
- <N> bears the language property:
`<N> <http://purl.org/dc/elements/1.1/language> "fr"^^<http://www.w3.org/2001/XMLSchema#language>`
- <N> bears also the formatted text of the note through the `http://eurovoc.europa.eu/schema#noteLiteral` predicate. The value for this datatype property is XMLLiteral.

(<N> bears also other properties for authoring and versioning information).

This modelization was discussed in Dagstuhl but not included in the specification. I intend to describe it in a best practice document.

In some cases, we don't have a formatted text for the note, just a string. It would be artificial to present the string as an XHTML fragment, so what is needed is a string datatype property:

`<N> xkos:plainText "Ce poste comprend..."`

I think it is important to standardize the name of this property in order to have a uniform way of accessing the note texts across XKOS implementations.

**Comment by FranckCo** [comment]
Resolved in commits d5684f3, 259b935 and 4056e48.
