### ISSUE TITLE
Preferred label

### ISSUE THREAD

**Issue by delcada** [linked-statistics/xkos#42]
Concerning the text below:

In SKOS, there are many properties that allow one to record the various designations of a concept: prefLabel; altLabel; hiddenLabel. All are repeatable for different languages. One drawback is the insistence on a preferred label. For statistical classifications, the preference for some designation depends on the context of its use. Codes are used for classification, data representation, and data interoperability. Short labels, a kind of term, are used in reports and the stubs of tables. Long labels, another kind of term, which are intended to convey much of the meaning of the designated cateory, are used in semantic interoperability. Each is “preferred” in its main areas of use.

can't we recommend that the official label be the "preferred" one by definition and other labels should be used as "ALT" or similar labels (as is implicitly suggested in the example presented under point 8.1).

See also related discussion about self-explanatory texts under #43

**Comment by tfrancart** [comment]
Section 8.1 already contains the sentence : "In all cases the skos:prefLabel property is used to express the full label".
Will add the adjective "official" to make this even more explicit, and will add a reference from section 2.2 to section 8.1
