### ISSUE TITLE
Versioning of classifications schemes

### ISSUE THREAD

**Issue by makxdekkers** [linked-statistics/xkos#62]
It is not entirely clear how the versioning of classifications schemes works in the XKOS model. The short statement in the first paragraph in section 7 does not explain how this is envisaged. In a more traditional approach, a new version of a classification scheme would contain a complete set of items, some of them duplicates of items in the previous version, others modified, added or deleted; correspondences then relate the items in the old version to the items in the new one. In a SKOS approach, Concepts that do not change are not duplicated but can simply be ‘inScheme’ of more than one ConceptScheme. What is the model in XKOS?

**Comment by tfrancart** [comment]
See also #54
