### ISSUE TITLE
Prescription on the use of other vocabularies when creating a XKOS classification or correspondence table

### ISSUE THREAD

**Issue by laurentlefort** [linked-statistics/xkos#69]
Section 8 includes a number of recommendations on how to document an XKOS artefact (using annotation properties such as skosxl:label) but the non XKOS properties which can be used to annotate a classification are not listed in Table 1. 
Would it be possible to add a listing of which properties are recommended for which types of XKOS (and SKOS) classes or a thematic one on the model of the one developed for the AgroPortal metadata: [http://htmlpreview.github.io/?https://github.com/agroportal/documentation/blob/master/metadata/Metadata%20for%20AgroPortal.html](http://htmlpreview.github.io/?https://github.com/agroportal/documentation/blob/master/metadata/Metadata%20for%20AgroPortal.html)

**Comment by laurentlefort** [comment]
Section 8 includes a number of recommendations on how to document an XKOS artefact (using annotation properties such as skosxl:label) but the non XKOS properties which can be used to annotate a classification are not listed in Table 1.
 Would it be possible to add a listing of which properties are recommended for which types of XKOS (and SKOS) classes or a thematic one on the model of the one developed for the AgroPortal metadata: http://htmlpreview.github.io/?https://github.com/agroportal/documentation/blob/master/metadata/Metadata%20for%20AgroPortal.html

**Comment by tfrancart** [comment]
Example of description of statistical classifications in RDF will be provided in a Best Practice document.
