### ISSUE TITLE
Assumption that the reader is familiar with statistical classification concepts in use in this community of practice inherited

### ISSUE THREAD

**Issue by laurentlefort** [linked-statistics/xkos#72]
In particular:  best practice guidelines, Neuchatel model, GSIM

This is an issue also behind Antoine Isaac's remarks in his earlier review of XKOS in 2014 [https://groups.google.com/forum/#!topic/ddi-rdf-vocabulary/v6CrJRkk5l0](https://groups.google.com/forum/#!topic/ddi-rdf-vocabulary/v6CrJRkk5l0) (recorded as ISSUES 28-30 here).

Here are a few improvement suggestions in this area (split into separate issues for your convenience)
(see also the next three issues) 

Add some best practice guidelines references in section 2, e.g. the ones suggested below (or better ones),

- [Best practice guidelines for developing International Statistical Classifications](http://unstats.un.org/unsd/class/intercop/expertgroup/2011/AC234-6.PDF) (2011)   
- or [Guidelines on International Classifications for Agricultural Statistics](http://gsars.org/wp-content/uploads/2015/12/Guidelines-for-Int-Classifications-on-Agricultural-Statistics-web.pdf
) (2015)

**Comment by nichtich** [comment]
See also #82
