### ISSUE TITLE
Support to the management of classifications over time

### ISSUE THREAD

**Issue by laurentlefort** [linked-statistics/xkos#78]
(5.2): “the precise definition of what constitutes a version of a skos:ConceptScheme, skos:Collection or skos:Concept is out of scope for this model, but validity and version information can be represented in simple ways”.

So, one important use case (story) for XKOS is to capture mappings between these different artefacts via correspondence but it is unclear where to stop.

My understanding is that a number of XKOS concepts e.g. the xkos:variant property and possibly some of the temporal relationships in section 9 have been included in XKOS to support sequential or parallel publications/usages of a classification (its lifecycle as further defined in GSIM but also in other documents such the “Copenhagen mapping”). 

I am aware that one of the reference implementations of XKOS (ISTAT) is using XKOS in conjunction with a number of other W3C vocabularies (Prov, DCAT, ADMS) and that this convergence is a desired feature in other parts of the SemStats community (e.g. work done in DDI 4 sprints). 
But because this experience (where to use XKOS, where to use Prov) is not described in the specification, it is hard to judge if what is presently included in XKOS (esp. xkos:variant) qualifies as a minimal viable product or not for the representation in “simple way” of validity and version information.   

This leads me to ask two questions: 
-	Are there such MVP implementations of XKOS which uses xkos:variant? 
-	If so, can these implementations be included as a richer example as suggested in ISSUE YY?

My second remark is that it would be good to more formally assess whether the direction taken by XKOS is compatible with the other ongoing developments nearby and evaluate existing “simple way” of describing  of validity and version information (to not unduly constrain future developments). 

This issue is related to my former question on the definition of the relationship of XKOS with GSIM with GSIM introducing richer  concepts for this particular use case e.g. different types of variants: http://www.statcan.gc.ca/eng/subjects/standard/napcs/notice/classificationvariant 

Publishing Official Classification in Linked Open data (ISTAT) http://dia.uniroma3.it/~maccioni/files/semstats2014.pdf 

Dagstuhl Sprint, October 2016 (Week One) https://ddi-alliance.atlassian.net/wiki/pages/viewpage.action?pageId=31260690 

GSIM Statistical Classification Model http://www1.unece.org/stat/platform/download/attachments/97356504/Statistical%20Classification%20Model%201_1%20(with%20updated%20links).docx?version=1&modificationDate=1481722176140&api=v2). 

The Copenhagen Mapping Implementing the GSIM Statistical Classification Model with DDI Lifecycle 
http://cdn.colectica.com/TheCopenhagenMapping-Draft.pdf 

A good place to check available “simple ways” is: http://htmlpreview.github.io/?https://github.com/agroportal/documentation/blob/master/metadata/Metadata%20for%20AgroPortal.html 
- for example, the door-prefixed properties are interesting (DOOR: toward a formalization of ontology relations: http://oro.open.ac.uk/24326/1/keod09.pdf ) but I have not found where to fetch the ontology source from

**Comment by tfrancart** [comment]
- The notion of "variant" is extracted from the Neuchatel model. Real-life working examples of "variants" exists at least in France, Canada and US.
- The XKOS way of describing the versioning of classification over time attempts to capture how things are done in statistical agencies.
- Although the XKOS documentation already gives some indication on this, more details on how to manage classifications over time can be further described in a best practice document
