### ISSUE TITLE
Absence of recommendation on how to annotate concepts association at the linkset level (correspondence level)

### ISSUE THREAD

**Issue by laurentlefort** [linked-statistics/xkos#80]
XKOS does not propose any mechanism to give the user the possibility to provide details on how correspondence links have been established at the linkset level e.g. with an approach comparable to what the Open PHACTS community has defined to capture mapping justifications (with the help of the property void:linkPredicate and possibly bdb:linksetJustification) for the whole linkset.

Are there plans for encouraging XKOS users to reuse or to adapt this approach to correspondences?

For more information on Open PHACTS guidelines, see: 

OpenPHACTS guidelines
·	OpenPHACTS (2013) Dataset Descriptions for the Open Pharmacological Space 
·	Expressing mapping relationships: http://www.openphacts.org/specs/2013/WD-datadesc-20130912/#mapping-representation 
·	BridgeDB mapping vocabulary http://www.openphacts.org/specs/2013/WD-datadesc-20130912/#bridgedb 
·	BridgeDb DataSource Ontology http://vocabularies.bridgedb.org/ops (bdb prefix used above)
·	BridgeDb:framework for finding and mapping equivalent database identifiers http://www.bridgedb.org/
·	Marshall et al Emerging practices for mapping and linking life sciences data using RDF — A case series http://dx.doi.org/10.1016/j.websem.2012.02.003

**Comment by tfrancart** [comment]
- XKOS does not prescribe the description of a xkos:Correspondence
- Usage examples can be given in a best practices document
