### ISSUE TITLE
Limitations of using a single class (xkos:ConceptAssociation) to capture data about N-ary relationships 

### ISSUE THREAD

**Issue by laurentlefort** [linked-statistics/xkos#81]
My main concern in this scenario is that if the xkos:ConceptAssociation node is used as the “container” for richer attributes (e.g. justification or confidence level or even weights) then it will not be possible to know if the extra assertions attached to it (literals or links to other entities) should be interpreted as assertions valid for all source or target concepts attached to a node or only to some of them. 

An alternative to the currently proposed approach for xkos:ConceptAssociation would be to adapt the qualification pattern used in Prov-O as a mean to capture more information about each individual link.  

Prov-O Qualified terms: http://www.w3.org/TR/prov-o/#description-qualified-terms

**Comment by nichtich** [comment]
You cannot avoid a local closed world assumption in cases like this, so the information attached to a `xkos:ConceptAssociation` is about the whole set of diectly connected concepts. Prov-O Qualified terms can be useful when deriving normal skos mapping statements (e.g. `skos:exactMatch`) from a `xkos:ConceptAssociation`.

**Comment by tfrancart** [comment]
- Assertions expressed on a ConceptAssociation describes the entire ConceptAssociation as a whole; yet depending on the context a textual note on the ConceptAssociation might give an information on only one source or target concept;
- If appropriate, it is always possible to create multiple ConceptAssociation, each holding its dedicated description;
- Attributes can also be placed on the source or target Concepts;
