### ISSUE TITLE
Definition of "statistical classification"

### ISSUE THREAD

**Issue by catecara** [linked-statistics/xkos#82]
The definition of statistical classification is given in Sec 2.1. 

The definition should come with references. Eg., UNSD 2013. Mandate of the expert group on international statistical classifications. See also Guidelines on FAO. 2015. International Classifications for Agricultural Statistics. 

The definition given in the draft assumes that a SCS "is a hierarchical concept scheme", but a classification may be either flat or hierarchical, as mentioned further below in the text. Also, the assumption that is a “concept scheme” seems like a conceptual jump from a definition to its SKOS implementation. 

To clearly scope XKOS, the draft should mention the distinctive features of a statistical classification with respect to a generic classification. Currently, more emphasis is placed on the use of a statistical classification than on its structural features - this latter would make clear the limitations of SKOS as a vocabulary to express it. See also https://github.com/linked-statistics/xkos/issues/43 .

Two distinctive features of a statistical classification are 1) when non-flat, it allows for strict hierarchies only, i.e. no polihierarchies; 2) the categories in a classification are mutually exclusive. Feature 1 is not discussed, while feature 2 is addressed by property xkos:covers and its subproperties. I open a separate issue for those. 

The document should be checked for consistency in the use of “classification” and “statistical classification”.

**Comment by nichtich** [comment]
* Is there consensus on the "two distinctive features of a statistical classification"?
* The first feature "when non-flat, it allows for strict hierarchies only, i.e. no polihierarchies" can be reduced to "no polyhierarchies" or similar (e.g. "each concept is either a top concept or reachable from a top concept via exactly one path of skos:narrower statements") 
* How does "statistical classification" as used by XKOS relate to the definition at <https://en.wikipedia.org/wiki/Statistical_classification>?
