### ISSUE TITLE
Coverage of statistical classifications

### ISSUE THREAD

**Issue by catecara** [linked-statistics/xkos#83]
In section 5.4, three properties are defined:

1. skos:covers – to express the “field” covered by the classification, e.g. “economic activity, occupations, living organisms”. This property then has to do with the domain, or subject of the classification. -> If so, it could be replaced by other well-known properties, as suggested elsewhere

2. xkos:coversExhaustively – to express the fact that “the coverage of the given field is complete (i.e., all notions in the filed can potentially be classified under the classification). ” -> The problem with this property is that the definition of what is exhaustive and what is not highly depends on time and on the intended use of the classification. Likely, all classifications in their present version are to be considered exhaustive, except when gaps are identified and a new version of the classification is produced. 
 
3. xkocs:coversMutuallyExclusively – to express the fact  that categories (classification items in the document) at the same level in the classification are mutually exclusive. I have doubts about introducing properties of this type in an SKOS-based vocabulary, as their informative value is limited by the lack of logical axioms à la OWL.

**Comment by tfrancart** [comment]
- We acknowledge that exhaustivity depends on the timeframe and intended use.
- We do think classification providers will use these flags to publish their classifications, and that these flags can serve as a basis for selecting proper classifications for a given domain.
- These properties serve as a description of a certain level of quality of the classification, and we believe they are useful even without logical axioms associated to them.
