### ISSUE TITLE
Refinements of skos:related

### ISSUE THREAD

**Issue by catecara** [linked-statistics/xkos#85]
In Sec 9, a few refinements to skos:related are introduced, namely xkos:caused (xkos:cuasedBy) and xkos:precedes (xkos:succeeds) (and xkos:previous, xkos:next). 

The rationale and intended meaning/use of these properties is not stated. Also, such properties bring XKOS outside the scope of an RDF/SKOS extension and would rather require logical axioms. Discussion related to issue https://github.com/linked-statistics/xkos/issues/76

**Comment by nichtich** [comment]
Furthermore [skos:related is a symmetric property](https://www.w3.org/TR/skos-reference/#L2255) so the given refinements contradict the SKOS specification. I suppose the refinements should be non-symmetric *alternatives* to skos:related instead.

**Comment by tfrancart** [comment]
A subProperty of a symmetric property is not necessarily symmetric. The [paragraph of the SKOS specification being referred to](https://www.w3.org/TR/skos-reference/#L2255) makes this explicit :

> Note that, although skos:related is a symmetric property, this condition does not place any restrictions on sub-properties of skos:related (i.e., sub-properties of skos:related could be symmetric, not symmetric or antisymmetric, and still be consistent with the SKOS data model).

**Comment by tfrancart** [comment]
The rationale of the subProperties of skos:related is stated in the introduction; they are directly derived from ISO standards on classifications :

> The proposed extensions to SKOS were not only guided by the needs of the statistical community but by requirements laid out in ISO standards on terminology, such as ISO 704:2009 ([ISO704]) and ISO 1087-1:2000 ([ISO1087]). These standards describe and define the constructs and relations necessary for concept management and a more complete description of statistical classifications.

Another reference to these ISO standards will be inserted in Section 9 to make this explicit.

**Comment by tfrancart** [comment]
The refinement of skos:related is clearly allowed by SKOS. As a matter of fact, the causal relation is precisely an example of extension given by SKOS itself in [Example 31](https://www.w3.org/TR/skos-reference/#L2255).

```
<cause> rdf:type owl:ObjectProperty ;
  rdfs:subPropertyOf skos:related .

<effect> rdf:type owl:ObjectProperty ;
 rdfs:subPropertyOf skos:related ;
  owl:inverseOf <cause> .

<A> <cause> <B> .
```

This addresses use-cases (often met) of "I want to stay in the SKOS/terminology world but I want to take one small step in introducing more semantics without migrating everything in OWL".
