### ISSUE TITLE
Concept association, case m:n

### ISSUE THREAD

**Issue by catecara** [linked-statistics/xkos#86]
The m:n correspondence between classification items in classification systems can be expressed in the following way (example below taken from Guidelines on FAO. 2015. International Classifications for Agricultural Statistics): 

Let items a, b belong to Classification A; item c, d belong to Classification B. 
e.g. 
a = meat of cattle and buffalo fresh
b = meat of cattle and buffalo frozen
c = meat of cattle fresh and frozen
d = meat of buffalo fresh and frozen

Then,  
(i) a corresponds to (c, d)
(ii) b corresponds to (c, d)
(iii) and together : a+b = c +d (in terms of classified data)

The current proposal seem to capture (iii) but not (i) and (ii). The rendering of (i) and (ii) should be discussed.

**Comment by nichtich** [comment]
What exactely is meant by "(c, d)" and "c +d"?

On 20. März 2017 16:05:22 MEZ, catecara <notifications@github.com> wrote:
>The m:n correspondence between classification items in classification
>systems can be expressed in the following way (example below taken from
>Guidelines on FAO. 2015. International Classifications for Agricultural
>Statistics): 
>
>Let items a, b belong to Classification A; item c, d belong to
>Classification B. 
>e.g. 
>a = meat of cattle and buffalo fresh
>b = meat of cattle and buffalo frozen
>c = meat of cattle fresh and frozen
>d = meat of buffalo fresh and frozen
>
>Then,  
>(i) a corresponds to (c, d)
>(ii) b corresponds to (c, d)
>(iii) and together : a+b = c +d (in terms of classified data)
>
>The current proposal seem to capture (iii) but not (i) and (ii). I
>wonder whether all three correspondences should be rendered.  
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/linked-statistics/xkos/issues/86

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by catecara** [comment]
- a corresponds to (c, d) in the sense that the classification items (and so their codes) "meat of cattle and buffalo fresh" partially correspond to "meat of cattle fresh and frozen" AND "meat of buffalo fresh and frozen". In particular this means that when passing from one classification system to the another (from A to B) the data classified as "a" will have to be re-allocate to c and d. Some conversion factor will be used.

- (a+b) = (c+d) refers to the fact that when doing a conversion from a classification system to another (from A to B), the data re-allocated according to classification B will have to be equal to the data allocated in the original classification, under the corresponding classification items. 

Hope the wording is clearer now.

**Comment by nichtich** [comment]
So there can be more correspondences:

1. a corresponds to c (partial overlap)
2. a corresponds to d (partial overlap)
3. b corresponds to c (partial overlap)
4. b corresponds to d (partial overlap)
5. a corresponds to (c+d) (a is narrower)
6. b corresponds to (c+d) (b is narrower)
7. (a+b) corresponds to (c+d) (exact)

**Comment by tfrancart** [comment]
- Different solutions exists for this :
  - Add extra properties or notes on the ConceptAssociation itself to further refine its description, e.g. conversion factors;
  - Create subclasses of ConceptAssociation, e.g. PartialCoverageConceptAssociation vs. ExactCoverageConceptAssociation;
  - Create multiple ConceptAssociations instead of a single one;
- The ability to capture precise percentage of how much a given source concept maps to a given target concepts was explicitely left out of scope as it added too much complexity in the model;
- We remain open for any suggestion in V2
